Repository thoth-station/pulp-pypi-sync-job, pull requests merged in 2021-06, with the labels that each got.

#3 Initial project import
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  app.py
  template/__init__.py
  template/version.py
Labels: size/XXL

#5 Fix missing bits in the project
  README.md
  README.rst
  pyproject.toml
Labels: approved, size/S

#7 Use Python 3.8
  Pipfile
  Pipfile.lock
Labels: size/XS

#14 Fix environment variable name
  app.py
Labels: size/XS

#17 ci updates for aicoe-ci
  .aicoe-ci.yaml
Labels: approved, size/S
